FROM mysql:8.0-oracle
#FROM mysql:8.0
#FROM mysql:5.7

# For ARM (M1) Mac
# You need to select an image that has an OS/ARCH of arm64/v8 from
# https://hub.docker.com/_/mysql/tags
# On 2022-10-06 I switched the default mysql image to the oracle one which looks like it is
# built for both AMD and ARM architectures and should compile for all platforms
# previously, some had reported using FROM mysql/mysql-server:5.7.28 for M1 macs.

